spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: cpf
    url: jdbc:mysql://localhost:3306/hello_mp?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl